language: go

go:
  - 1.9

sudo: false

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - DOCKER_USER=chiliec
    - DOCKER_IMAGE_NAME=golos-vote-bot

script:
  - go test -v ./...

before_deploy:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - ./coverage.sh
  - GOOS=linux go build -a --ldflags '-extldflags "-static"' -o bin/golos-vote-bot -i .
  - docker build -t $REPO:latest -f Dockerfile .
  - ./cc-test-reporter after-build

deploy:
  provider: script
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker push $DOCKER_USER/$DOCKER_IMAGE_NAME
  on:
    branch: master
