language: go

go:
  - 1.9

sudo: false

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - DOCKER_USER=chiliec
    - DOCKER_IMAGE_NAME=golos-vote-bot
    - REPO=${DOCKER_USER}/${DOCKER_IMAGE_NAME}
    - DEPLOY_HOST=174.138.52.21

addons:
  ssh_known_hosts: ${DEPLOY_HOST}

before_script:
  - go test -v ./...
  # coverage
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - for pkg in $(go list ./... | grep -v vendor); do
      go test -coverprofile=$(echo $pkg | tr / -).cover $pkg
    done
  - echo "mode: set" > c.out
  - grep -h -v "^mode:" ./*.cover >> c.out
  - rm -f *.cover
  - ./cc-test-reporter after-build

script:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $COMMIT ; fi`
  - GOOS=linux go build -a --ldflags '-extldflags "-static"' -o bin/golos-vote-bot -i .
  - docker build -t $REPO:$TAG -f Dockerfile .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $REPO

before_deploy:
  - cp deploy/id_rsa_docker.pub /tmp/id_rsa_docker.pub
  - openssl aes-256-cbc -K $encrypted_c59b19594e15_key -iv $encrypted_c59b19594e15_iv
    -in deploy/id_rsa_docker.enc -out /tmp/id_rsa_docker -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/id_rsa_docker
  - ssh-add /tmp/id_rsa_docker

deploy:
  provider: script
  script:
    - ssh -o StrictHostKeyChecking=no root@${DEPLOY_HOST} "docker pull $REPO:$TAG
      && docker stop ${DOCKER_IMAGE_NAME} || true
      && docker rm ${DOCKER_IMAGE_NAME} || true
      && docker run --name ${DOCKER_IMAGE_NAME} --restart=always -e TELEGRAM_TOKEN=$TELEGRAM_TOKEN -v /opt/golosbot/db:/opt/golosbot/db -w /opt/golosbot -d $REPO:$TAG ./golos-vote-bot"
  on:
    branch: master
