[[constraint]]
  branch = "master"
  name = "github.com/Chiliec/golos-go"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "gopkg.in/telegram-bot-api.v4"
  version = "4.6.0"
